# Generated by Django 5.2.3 on 2025-06-13 08:01

import django.db.models.deletion
import myapp.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('desk', models.CharField(max_length=250)),
                ('date_founded', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('writer', models.CharField(max_length=30)),
                ('desk', models.CharField(max_length=250)),
                ('file', models.ImageField(upload_to=myapp.utils.custom_upload_to)),
                ('date_founded', models.DateField()),
                ('musician', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.musician')),
            ],
        ),
    ]
