# Generated by Django 5.2.3 on 2025-06-16 03:59

import myapp.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='file',
            field=models.FileField(upload_to=myapp.utils.custom_upload_to),
        ),
    ]
