# Generated by Django 5.2.3 on 2025-06-16 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_music_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='musician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.musician'),
        ),
    ]
