# Generated by Django 5.2.3 on 2025-06-17 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_music_musician'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=30)),
                ('desk', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='music',
            name='genre',
            field=models.CharField(default='Pop', max_length=30),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='GenreMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.genre')),
                ('music', models.ManyToManyField(to='myapp.music')),
            ],
        ),
    ]
