# Generated by Django 5.2.3 on 2025-06-17 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_music_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genremusic',
            name='music',
        ),
        migrations.AddField(
            model_name='genremusic',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.genre'),
            preserve_default=False,
        ),
    ]
