# Generated by Django 5.2.3 on 2025-06-17 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_genremusic_music_genremusic_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genremusic',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.music'),
        ),
    ]
