# Generated by Django 5.2.3 on 2025-06-17 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_genremusic_music'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genremusic',
            name='genre',
        ),
        migrations.AddField(
            model_name='genremusic',
            name='genres',
            field=models.ManyToManyField(to='myapp.genre'),
        ),
    ]
