# Generated by Django 5.2.3 on 2025-06-17 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_genremusic_genre_genremusic_genres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genremusic',
            old_name='genres',
            new_name='genre',
        ),
    ]
