# Generated by Django 5.2.3 on 2025-06-17 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_genres_genremusic_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genremusic',
            old_name='genre',
            new_name='genres',
        ),
    ]
