# Generated by Django 5.2.3 on 2025-06-18 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_genre_genremusic_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='genres',
            field=models.ManyToManyField(to='myapp.genre'),
        ),
        migrations.DeleteModel(
            name='GenreMusic',
        ),
    ]
